version: "2.4"
services:
  heimdall:
    container_name: Heimdall
    image: linuxserver/heimdall:latest
    volumes:
      - heimdall_config:/config
    ports:
      - 1201:80
      - 443:443
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
  ghostfolio:
    container_name: Ghostfolio
    image: ghostfolio/ghostfolio:latest
    ports:
      - 3333:3333
    restart: always
    environment:
      - DATABASE_URL=postgres://ztorm:lekkerding@192.168.178.238:5433/ghostfolio?sslmode=prefer
      - NODE_ENV=production
      - ACCESS_TOKEN_SALT="u1em9x1zdz9numb"
      - JWT_SECRET_KEY="1nqf0axvpufn41k"
      - REDIS_HOST=192.168.178.238
      - REDIS_PORT=6379
